on:
  push:
    branches: [ "main" ]

jobs:
  build:

    steps:
      - uses: actions/checkout@v4
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'




        with:
